version: '3.3'

services:
        db:
                image: postgres
                volumes:
                        - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
        web:
                env_file:
                        - docker.env
                build: .
                command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000'
                volumes:
                        - .:/code
                ports:
                        - '8000:8000'
                depends_on:
                        - db


