version: '3.3'

services:
        db:
            image: postgres:12.1-alpine
            env_file: 
                - settings.env
            volumes:
                - ./motherducker/pgdata:/var/lib/postgresql/data
        web:
            build: ./motherducker
            env_file:
                - settings.env
            volumes:
                - ./motherducker:/opt/motherducker
                - static_volume:/var/www/motherducker/static
            command: >
                sh -c
                'python manage.py makemigrations &&
                 python manage.py migrate &&
                 python manage.py loaddata payloads_fixture.json &&
                 python manage.py collectstatic --no-input &&

                 gunicorn motherducker.wsgi:application --workers=2 --bind=[::]:80'
            expose:
                - 80
            depends_on:
                - db
            restart: on-failure
        nginx:
            build: ./nginx
            volumes:
                - static_volume:/var/www/motherducker/static
            ports:
                - 80:80
                - 443:443
            depends_on:
                - web

volumes:
    static_volume: