version: '3.3'

services:
        db:
            image: postgres
            environment:
                - POSTGRES_DB=${DB_NAME}
                - POSTGRES_USER=${DB_USER}
                - POSTGRES_PASSWORD=${DB_PASS}
            volumes:
                - ./motherducker/data:/var/lib/postgresql/data
        web:
            environment:
                - SECRET=${SECRET}
                - WEB_HOST=${WEB_HOST}
                - DB_NAME=${DB_NAME}
                - DB_USER=${DB_USER}
                - DB_PASS=${DB_PASS}
                - DB_HOST=${DB_HOST}
                - DB_PORT=${DB_PORT}
            build:
                context: .
                dockerfile: Dockerfile.prod
            command: "gunicorn --bind 0.0.0.0:8000 motherducker.wsgi:application"
            volumes:
                - .:/code
                - static_volume:/var/www/dilkovak-ubuntuvm.mshome.net/static/static
            expose:
                - '${WEB_PORT}'
            depends_on:
                - db
            restart: on-failure
        nginx:
            build: ./nginx
            volumes:
                - static_volume:/var/www/dilkovak-ubuntuvm.mshome.net/static/static
            ports:
                - 80:80
            depends_on:
                - web

volumes:
  static_volume: